tunnel: 1db67372-6e40-4f7f-9601-8338ddc7e33c
credentials-file: /root/.cloudflared/1db67372-6e40-4f7f-9601-8338ddc7e33c.json

ingress:
  - hostname: wock.best
    service: http://localhost:3000

  - hostname: jimnjobrown.com
    service: http://localhost:5000

  - service: http_status:404